
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 50;
  public static final int MENOSMENOS = 51;
  public static final int PORIGUAL = 54;
  public static final int CHAR = 39;
  public static final int POR = 26;
  public static final int GE = 45;
  public static final int CCOR = 21;
  public static final int ENTERO = 32;
  public static final int DIVIGUAL = 55;
  public static final int INT = 37;
  public static final int FOR = 11;
  public static final int MINUS = 14;
  public static final int ACOR = 20;
  public static final int CP = 5;
  public static final int AND = 42;
  public static final int NOT = 41;
  public static final int LT = 46;
  public static final int IGUAL = 15;
  public static final int MASIGUAL = 52;
  public static final int OR = 43;
  public static final int IN = 22;
  public static final int LETRA = 34;
  public static final int DIV = 27;
  public static final int IF = 9;
  public static final int LE = 47;
  public static final int EOF = 0;
  public static final int IGACION = 29;
  public static final int error = 1;
  public static final int COMA = 16;
  public static final int MENOS = 25;
  public static final int MOD = 28;
  public static final int IDENT = 8;
  public static final int EQ = 49;
  public static final int CLL = 7;
  public static final int REAL = 33;
  public static final int ELVIS = 31;
  public static final int DOSPUN = 30;
  public static final int ELSE = 10;
  public static final int TO = 17;
  public static final int WHILE = 2;
  public static final int FLOAT = 38;
  public static final int MENOSIGUAL = 53;
  public static final int NE = 48;
  public static final int STRING = 40;
  public static final int ALL = 6;
  public static final int DOWNTO = 18;
  public static final int TEXTO = 36;
  public static final int UNICODE = 35;
  public static final int GT = 44;
  public static final int AP = 4;
  public static final int PRINT = 12;
  public static final int LENGTH = 23;
  public static final int DO = 3;
  public static final int STEP = 19;
  public static final int PYC = 13;
  public static final int MAS = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "WHILE",
  "DO",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "IDENT",
  "IF",
  "ELSE",
  "FOR",
  "PRINT",
  "PYC",
  "MINUS",
  "IGUAL",
  "COMA",
  "TO",
  "DOWNTO",
  "STEP",
  "ACOR",
  "CCOR",
  "IN",
  "LENGTH",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MOD",
  "IGACION",
  "DOSPUN",
  "ELVIS",
  "ENTERO",
  "REAL",
  "LETRA",
  "UNICODE",
  "TEXTO",
  "INT",
  "FLOAT",
  "CHAR",
  "STRING",
  "NOT",
  "AND",
  "OR",
  "GT",
  "GE",
  "LT",
  "LE",
  "NE",
  "EQ",
  "MASMAS",
  "MENOSMENOS",
  "MASIGUAL",
  "MENOSIGUAL",
  "PORIGUAL",
  "DIVIGUAL"
  };
}

