package Ejercicio_2.Ejercicio_2_1;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 17 17:24:06 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 2;
  public static final int error = 1;
  public static final int EOF = 0;
}

