package CalculadoraMatriz;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 19 13:51:23 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 11;
  public static final int CCOR = 10;
  public static final int COMA = 13;
  public static final int MENOS = 3;
  public static final int CP = 7;
  public static final int EOLN = 12;
  public static final int POR = 4;
  public static final int EOF = 0;
  public static final int PYC = 5;
  public static final int MAS = 2;
  public static final int ACOR = 9;
  public static final int NUMERO = 8;
  public static final int error = 1;
  public static final int AP = 6;
}

