package Ejercicio_3.Ejercicio_3_1;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 17 12:06:40 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 6;
  public static final int MAS = 2;
  public static final int error = 1;
  public static final int MENOS = 5;
  public static final int DIV = 4;
  public static final int POR = 3;
  public static final int EOF = 0;
}

