package Ejercicio_1.Ejercicio_1_2;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 16 12:51:16 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOUBLE = 3;
  public static final int error = 1;
  public static final int IDENT = 5;
  public static final int EOF = 0;
  public static final int PYC = 4;
  public static final int INT = 2;
}

