package Calculadora;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 16 12:48:33 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 8;
  public static final int LP = 7;
  public static final int MENOS = 5;
  public static final int EOLN = 9;
  public static final int POR = 3;
  public static final int EOF = 0;
  public static final int MAS = 2;
  public static final int NUMERO = 10;
  public static final int DIV = 4;
  public static final int error = 1;
  public static final int RP = 6;
}

