package Ejercicio_2;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 10;
  public static final int INT = 2;
  public static final int IDENT = 8;
  public static final int LONG = 3;
  public static final int BOOLEAN = 7;
  public static final int EOF = 0;
  public static final int PYC = 9;
  public static final int DOUBLE = 5;
  public static final int error = 1;
  public static final int FLOAT = 4;
  public static final int CHAR = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "LONG",
  "FLOAT",
  "DOUBLE",
  "CHAR",
  "BOOLEAN",
  "IDENT",
  "PYC",
  "COMA"
  };
}

