package Ejercicio_3;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 9;
  public static final int DIVIDE = 5;
  public static final int CP = 7;
  public static final int SUMA = 2;
  public static final int EOF = 0;
  public static final int PYC = 8;
  public static final int NUMERO = 10;
  public static final int MULTIPLICA = 4;
  public static final int error = 1;
  public static final int RESTA = 3;
  public static final int AP = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULTIPLICA",
  "DIVIDE",
  "AP",
  "CP",
  "PYC",
  "COMA",
  "NUMERO"
  };
}

