package Ejercicio_3.Ejercicio_3_3;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 17 13:17:52 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 5;
  public static final int COMA = 4;
  public static final int CC = 3;
  public static final int error = 1;
  public static final int AC = 2;
  public static final int EOF = 0;
}

