package Ejercicio_1.Ejercicio_1_3;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 16 13:53:29 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENT = 9;
  public static final int MENOS = 3;
  public static final int CP = 7;
  public static final int POR = 4;
  public static final int EOF = 0;
  public static final int MAS = 2;
  public static final int NUMERO = 8;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int AP = 6;
}

