package Ejercicio_1.Ejercicio_1_1;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 15 16:19:20 GMT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 2;
  public static final int error = 1;
  public static final int IDENT = 3;
  public static final int EOF = 0;
}

