
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 07 19:46:36 GMT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 47;
  public static final int MENOSMENOS = 48;
  public static final int PORIGUAL = 51;
  public static final int CHAR = 37;
  public static final int POR = 25;
  public static final int GE = 42;
  public static final int CCOR = 21;
  public static final int ENTERO = 31;
  public static final int DIVIGUAL = 52;
  public static final int INT = 35;
  public static final int FOR = 11;
  public static final int MINUS = 14;
  public static final int ACOR = 20;
  public static final int CP = 5;
  public static final int AND = 39;
  public static final int NOT = 38;
  public static final int LT = 43;
  public static final int IGUAL = 15;
  public static final int MASIGUAL = 49;
  public static final int OR = 40;
  public static final int IN = 22;
  public static final int LETRA = 33;
  public static final int DIV = 26;
  public static final int IF = 9;
  public static final int LE = 44;
  public static final int EOF = 0;
  public static final int IGACION = 28;
  public static final int error = 1;
  public static final int COMA = 16;
  public static final int MENOS = 24;
  public static final int MOD = 27;
  public static final int IDENT = 8;
  public static final int EQ = 46;
  public static final int CLL = 7;
  public static final int REAL = 32;
  public static final int ELVIS = 30;
  public static final int DOSPUN = 29;
  public static final int ELSE = 10;
  public static final int TO = 17;
  public static final int WHILE = 2;
  public static final int FLOAT = 36;
  public static final int MENOSIGUAL = 50;
  public static final int NE = 45;
  public static final int ALL = 6;
  public static final int DOWNTO = 18;
  public static final int UNICODE = 34;
  public static final int GT = 41;
  public static final int AP = 4;
  public static final int PRINT = 12;
  public static final int DO = 3;
  public static final int STEP = 19;
  public static final int PYC = 13;
  public static final int MAS = 23;
}

